# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

SC_func <- function(Time, censor, wgt) {
    .Call(`_QRLL_SC_func`, Time, censor, wgt)
}

